CREATE TABLE Geracao (
    cod_bilhete VARCHAR2(30) NOT NULL,
    data_hora_geracao INTEGER NOT NULL
)

DROP TABLE GERACAO;

SELECT * FROM GERACAO;

DESC GERACAO;

TRUNCATE TABLE GERACAO;
TRUNCATE TABLE RECARGA;
TRUNCATE TABLE UTILIZACAO;
TRUNCATE TABLE HISTORICO_RECARGA;
TRUNCATE TABLE HISTORICO_UTILIZACAO;