CREATE TABLE UTILIZACAO (
    cod_bilhete VARCHAR2(30) NOT NULL,
    tipo_utilizacao VARCHAR2(30) NOT NULL,
    data_utilizacao DATE NOT NULL,
    hora_utilizacao VARCHAR2(30) NOT NULL
)

TRUNCATE TABLE UTILIZACAO;

DROP TABLE UTILIZACAO;

SELECT * FROM UTILIZACAO;